[package]
name = "factor"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
license-file = "LICENSE"

[dependencies]
clap = { version = "4.5.21", features = ["derive", "env"] }
tokio = { version = "1.41", features = ["full"] }
reqwest = { version = "0.12", features =["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "3.11"
anyhow = "1.0"
base64 = "0.22"
regex = "1.11"
toml = "0.8"
async-trait = "0.1"
dirs = "5.0"
strum_macros = "0.26"
http = "1.1.0"
kube = { version = "0.97.0", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.23.0", features = ["latest"] }
chrono = "0.4"
jsonwebtoken = "9.3"
notify = "7.0.0"
tempfile = "3.14.0"
pingora-core = "0.4.0"
pingora-proxy = "0.4.0"
pingora-http = "0.4.0"
biscuit = "0.7.0"
shellexpand = "3.1.0"
dotenvy = "0.15.7"
pingora = "0.4.0"
ngrok = "0.13.1"
rsa = "0.9.7"
sha2 = "0.10.8"
rand = "0.8.5"
num-bigint = "0.4.6"
env_logger = "0.11.5"
