[unstable]
codegen-backend = true

[profile.fast-dev]
inherits = "dev"
codegen-backend = "cranelift"
rustflags = ["-Z", "threads=8"]

[alias]
lint-all = ["--all-features", "--all-targets", "clippy"]
check-all = ["--all", "--profile", "check", "fast-dev"]
